In [3]:
# 1. Implement Recursive Depth First Search Algorithm. Read the undirected unweighted graph from a .csv file. 

import csv

def read_graph_from_csv(filename):
    graph = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            node1, node2 = row
            if node1 not in graph:
                graph[node1] = []
            if node2 not in graph:
                graph[node2] = []
            graph[node1].append(node2)
            graph[node2].append(node1)
    return graph

def dfs_recursive(graph, node, visited):
    visited.add(node)
    print(node, end = ' ')
    for neighbor in graph[node]:
        if neighbor not in visited:
            dfs_recursive(graph, neighbor, visited)

def main():
    filename = 'edges.csv' 
    graph = read_graph_from_csv(filename)
    visited = set()
    start_node = list(graph.keys())[0]
    print("DFS Traversal:", end=' ')
    dfs_recursive(graph, start_node, visited)

if __name__ == "__main__":
    main()

DFS Traversal: A B C D E 

In [5]:
# 2. Implement Non-Recursive Depth First Search Algorithm. Read the undirected unweighted graph from user. 

def read_graph_from_user():
    graph = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2 = input("Enter edge (node1 node2): ").split()
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append(node2)
        graph[node2].append(node1)
    return graph

def dfs_non_recursive(graph, start_node):
    visited = set()
    stack = [start_node]
    while stack:
        node = stack.pop()
        if node not in visited:
            visited.add(node)
            print(node, end=' ')
            for neighbor in graph[node]:
                if neighbor not in visited:
                    stack.append(neighbor)

def main():
    graph = read_graph_from_user()
    start_node = input("Enter start node: ")
    print("DFS Traversal:", end=' ')
    dfs_non_recursive(graph, start_node)

if __name__ == "__main__":
    main()

Enter number of edges:  5
Enter edge (node1 node2):  0 1
Enter edge (node1 node2):  0 2
Enter edge (node1 node2):  1 2
Enter edge (node1 node2):  2 3
Enter edge (node1 node2):  2 4
Enter start node:  0


DFS Traversal: 0 2 4 3 1 

In [6]:
# 3. Implement Breadth First Search Algorithm. Read the undirected unweighted graph from user. 

from collections import deque

def read_graph_from_user():
    graph = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2 = input("Enter edge (node1 node2): ").split()
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append(node2)
        graph[node2].append(node1)
    return graph

def bfs(graph, start_node):
    visited = set()
    queue = deque([start_node])
    visited.add(start_node)
    while queue:
        node = queue.popleft()
        print(node, end=' ')
        for neighbor in graph[node]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

def main():
    graph = read_graph_from_user()
    start_node = input("Enter start node: ")
    print("BFS Traversal:", end=' ')
    bfs(graph, start_node)

if __name__ == "__main__":
    main()

Enter number of edges:  5
Enter edge (node1 node2):  0 1
Enter edge (node1 node2):  0 2
Enter edge (node1 node2):  1 2
Enter edge (node1 node2):  2 3
Enter edge (node1 node2):  2 4
Enter start node:  0


BFS Traversal: 0 1 2 3 4 

In [9]:
# 4. Implement Best First Search Algorithm. Read the directed unweighted graph and the heuristic values from user.

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2 = input("Enter edge (node1 node2): ").split()
        if node1 not in graph:
            graph[node1] = []
        graph[node1].append(node2)
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def best_first_search(graph, start, goal, heuristics):
    visited = set()
    pq = PriorityQueue()
    pq.put((heuristics[start], start))
    while not pq.empty():
        _, node = pq.get()
        if node in visited:
            continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            break
        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                pq.put((heuristics[neighbor], neighbor))

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    print("Best First Search Path:", end=' ')
    best_first_search(graph, start, goal, heuristics)

if __name__ == "__main__":
    main()

Enter number of edges:  6
Enter edge (node1 node2):  A B
Enter edge (node1 node2):  A C
Enter edge (node1 node2):  B D
Enter edge (node1 node2):  C D
Enter edge (node1 node2):  C E
Enter edge (node1 node2):  E G
Enter all nodes (space-separated):  A B C D E G
Enter heuristic for A:  6
Enter heuristic for B:  4
Enter heuristic for C:  5
Enter heuristic for D:  2
Enter heuristic for E:  3
Enter heuristic for G:  0
Enter start node:  A
Enter goal node:  G


Best First Search Path: A B D C E G 

In [10]:
# 5. Implement Best First Search Algorithm. Read the undirected weighted graph and the heuristic values from user

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2, weight = input("Enter edge (node1 node2 weight): ").split()
        weight = int(weight)
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append((node2, weight))
        graph[node2].append((node1, weight))
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def best_first_search(graph, start, goal, heuristics):
    visited = set()
    pq = PriorityQueue()
    pq.put((heuristics[start], start))
    while not pq.empty():
        _, node = pq.get()
        if node in visited:
            continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            break
        for neighbor, _ in graph.get(node, []):
            if neighbor not in visited:
                pq.put((heuristics[neighbor], neighbor))

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    print("Best First Search Path:", end=' ')
    best_first_search(graph, start, goal, heuristics)

if __name__ == "__main__":
    main()

Enter number of edges:  7
Enter edge (node1 node2 weight):  S A 2
Enter edge (node1 node2 weight):  S B 3
Enter edge (node1 node2 weight):  A C 4
Enter edge (node1 node2 weight):  B D 5
Enter edge (node1 node2 weight):  C G 2
Enter edge (node1 node2 weight):  D G 3
Enter edge (node1 node2 weight):  B E 1
Enter all nodes (space-separated):  S A B C D E G  
Enter heuristic for S:  7
Enter heuristic for A:  6
Enter heuristic for B:  2
Enter heuristic for C:  4
Enter heuristic for D:  4
Enter heuristic for E:  6
Enter heuristic for G:  0
Enter start node:  S
Enter goal node:  G


Best First Search Path: S B D G 

In [ ]:
# 6. Implement Best First Search Algorithm. Read the undirected unweighted graph and the heuristic values from user.

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2 = input("Enter edge (node1 node2): ").split()
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append(node2)
        graph[node2].append(node1)
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def best_first_search(graph, start, goal, heuristics):
    visited = set()
    pq = PriorityQueue()
    pq.put((heuristics[start], start))
    while not pq.empty():
        _, node = pq.get()
        if node in visited:
            continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            break
        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                pq.put((heuristics[neighbor], neighbor))

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    print("Best First Search Path:", end=' ')
    best_first_search(graph, start, goal, heuristics)

if __name__ == "__main__":
    main()

In [ ]:
# 7. Implement Best First Search Algorithm. Read the directed weighted graph and the heuristic values from user.

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2, weight = input("Enter edge (node1 node2 weight): ").split()
        weight = int(weight)
        if node1 not in graph:
            graph[node1] = []
        graph[node1].append((node2, weight))
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def best_first_search(graph, start, goal, heuristics):
    visited = set()
    pq = PriorityQueue()
    pq.put((heuristics[start], start))
    while not pq.empty():
        _, node = pq.get()
        if node in visited:
            continue
        print(node, end=' ')
        visited.add(node)
        if node == goal:
            break
        for neighbor, _ in graph.get(node, []):
            if neighbor not in visited:
                pq.put((heuristics[neighbor], neighbor))

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    print("Best First Search Path:", end=' ')
    best_first_search(graph, start, goal, heuristics)

if __name__ == "__main__":
    main()

In [14]:
# 8. Implement A* algorithm. Read directed weighted graph and heuristic values from a .csv file. 

import csv
from queue import PriorityQueue

def read_graph_and_heuristics(filename):
    graph = {}
    heuristics = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if not row or row[0].startswith('#') or row[0] == 'node1':
                continue
            try:
                if len(row) == 2:  
                    node, h = row
                    heuristics[node] = int(h)
                elif len(row) == 3: 
                    node1, node2, weight = row
                    if node1 not in graph:
                        graph[node1] = []
                    graph[node1].append((node2, int(weight)))
            except ValueError:
                continue
    return graph, heuristics

def a_star(graph, start, goal, heuristics):
    pq = PriorityQueue()
    pq.put((0, start))
    g_score = {start: 0}
    came_from = {}
    while not pq.empty():
        _, node = pq.get()
        if node == goal:
            path = []
            while node in came_from:
                path.append(node)
                node = came_from[node]
            path.append(start)
            return path[::-1]
        for neighbor, weight in graph.get(node, []):
            tentative_g = g_score[node] + weight
            if neighbor not in g_score or tentative_g < g_score[neighbor]:
                came_from[neighbor] = node
                g_score[neighbor] = tentative_g
                f_score = tentative_g + heuristics.get(neighbor, 0)
                pq.put((f_score, neighbor))
    return []

def main():
    filename = 'graph.csv' 
    graph, heuristics = read_graph_and_heuristics(filename)
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    path = a_star(graph, start, goal, heuristics)
    print("A* Path:", ' -> '.join(path) if path else "No path found")

if __name__ == "__main__":
    main()

Enter start node:  A
Enter goal node:  D


A* Path: A -> B -> C -> D


In [17]:
# 9. Implement A* algorithm. Read directed weighted graph and heuristic values from user. 

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2, weight = input("Enter edge (node1 node2 weight): ").split()
        if node1 not in graph:
            graph[node1] = []
        graph[node1].append((node2, int(weight)))
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def a_star(graph, start, goal, heuristics):
    pq = PriorityQueue()
    pq.put((0, start))
    g_score = {start: 0}
    came_from = {}
    while not pq.empty():
        _, node = pq.get()
        if node == goal:
            path = []
            while node in came_from:
                path.append(node)
                node = came_from[node]
            path.append(start)
            return path[::-1]
        for neighbor, weight in graph.get(node, []):
            tentative_g = g_score[node] + weight
            if neighbor not in g_score or tentative_g < g_score[neighbor]:
                came_from[neighbor] = node
                g_score[neighbor] = tentative_g
                f_score = tentative_g + heuristics.get(neighbor, 0)
                pq.put((f_score, neighbor))
    return []

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    path = a_star(graph, start, goal, heuristics)
    print("A* Path:", ' -> '.join(path) if path else "No path found")

if __name__ == "__main__":
    main()

Enter number of edges:  6
Enter edge (node1 node2 weight):  A B 2
Enter edge (node1 node2 weight):  A C 3
Enter edge (node1 node2 weight):  B C 5
Enter edge (node1 node2 weight):  B D 7
Enter edge (node1 node2 weight):  C D 9
Enter edge (node1 node2 weight):  C E 5
Enter all nodes (space-separated):  A B C D E 
Enter heuristic for A:  5
Enter heuristic for B:  4
Enter heuristic for C:  3
Enter heuristic for D:  7
Enter heuristic for E:  9
Enter start node:  A
Enter goal node:  E


A* Path: A -> C -> E


In [19]:
# 10. Implement A* algorithm. Read undirected weighted graph and heuristic values from a .csv file. 

# Create graph.csv
with open('graph.csv', 'w') as f:
    f.write('# Edges: node1,node2,weight\nnode1,node2,weight\nA,B,2\nA,E,5\nB,C,3\nB,E,2\nC,D,1\nD,E,4\n# Heuristics: node,h_value\nA,10\nB,8\nC,5\nD,3\nE,0')

import csv
from queue import PriorityQueue

def read_graph_and_heuristics(filename):
    graph = {}
    heuristics = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if not row or row[0].startswith('#') or row[0] == 'node1':
                continue
            try:
                if len(row) == 2:
                    node, h = row
                    heuristics[node] = int(h)
                elif len(row) == 3:
                    node1, node2, weight = row
                    if node1 not in graph:
                        graph[node1] = []
                    if node2 not in graph:
                        graph[node2] = []
                    graph[node1].append((node2, int(weight)))
                    graph[node2].append((node1, int(weight)))
            except ValueError:
                continue
    return graph, heuristics

def a_star(graph, start, goal, heuristics):
    pq = PriorityQueue()
    pq.put((0, start))
    g_score = {start: 0}
    came_from = {}
    while not pq.empty():
        _, node = pq.get()
        if node == goal:
            path = []
            while node in came_from:
                path.append(node)
                node = came_from[node]
            path.append(start)
            return path[::-1]
        for neighbor, weight in graph.get(node, []):
            tentative_g = g_score[node] + weight
            if neighbor not in g_score or tentative_g < g_score[neighbor]:
                came_from[neighbor] = node
                g_score[neighbor] = tentative_g
                f_score = tentative_g + heuristics.get(neighbor, 0)
                pq.put((f_score, neighbor))
    return []

def main():
    filename = 'graph.csv'
    graph, heuristics = read_graph_and_heuristics(filename)
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    path = a_star(graph, start, goal, heuristics)
    print("A* Path:", ' -> '.join(path) if path else "No path found")

if __name__ == "__main__":
    main()

Enter start node:  A
Enter goal node:  E


A* Path: A -> E


In [2]:
# 11. Implement A* algorithm. Read undirected weighted graph and heuristic values from user. 

from queue import PriorityQueue

def read_graph_and_heuristics():
    graph = {}
    heuristics = {}
    n = int(input("Enter number of edges: "))
    for _ in range(n):
        node1, node2, weight = input("Enter edge (node1 node2 weight): ").split()
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append((node2, int(weight)))
        graph[node2].append((node1, int(weight)))
    nodes = input("Enter all nodes (space-separated): ").split()
    for node in nodes:
        h = int(input(f"Enter heuristic for {node}: "))
        heuristics[node] = h
    return graph, heuristics

def a_star(graph, start, goal, heuristics):
    pq = PriorityQueue()
    pq.put((0, start))
    g_score = {start: 0}
    came_from = {}
    while not pq.empty():
        _, node = pq.get()
        if node == goal:
            path = []
            while node in came_from:
                path.append(node)
                node = came_from[node]
            path.append(start)
            return path[::-1]
        for neighbor, weight in graph.get(node, []):
            tentative_g = g_score[node] + weight
            if neighbor not in g_score or tentative_g < g_score[neighbor]:
                came_from[neighbor] = node
                g_score[neighbor] = tentative_g
                f_score = tentative_g + heuristics.get(neighbor, 0)
                pq.put((f_score, neighbor))
    return []

def main():
    graph, heuristics = read_graph_and_heuristics()
    start = input("Enter start node: ")
    goal = input("Enter goal node: ")
    path = a_star(graph, start, goal, heuristics)
    print("A* Path:", ' -> '.join(path) if path else "No path found")

if __name__ == "__main__":
    main()

Enter number of edges:  4
Enter edge (node1 node2 weight):  A B 2
Enter edge (node1 node2 weight):  A C 3
Enter edge (node1 node2 weight):  B C 6
Enter edge (node1 node2 weight):  C D 3
Enter all nodes (space-separated):  A B C D 
Enter heuristic for A:  4
Enter heuristic for B:  5
Enter heuristic for C:  2
Enter heuristic for D:  3
Enter start node:  A 
Enter goal node:  D


A* Path: No path found


In [24]:
# 12. Implement Fuzzy set operations – union, intersection and complement. Demonstrate these operations with 3 fuzzy sets.

def fuzzy_union(set1, set2):
    return {k: max(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() | set2.keys()}

def fuzzy_intersection(set1, set2):
    return {k: min(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() & set2.keys()}

def fuzzy_complement(set1, universe):
    return {k: 1 - set1.get(k, 0) for k in universe}

def main():
    # Example fuzzy sets
    A = {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
    B = {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
    C = {'x1': 0.3, 'x2': 0.9, 'x3': 0.5}
    universe = {'x1', 'x2', 'x3'}
    
    print("Fuzzy Set A:", A)
    print("Fuzzy Set B:", B)
    print("Fuzzy Set C:", C)
    
    # Union
    union_AB = fuzzy_union(A, B)
    union_ABC = fuzzy_union(union_AB, C)
    print("Union (A ∪ B ∪ C):", union_ABC)
    
    # Intersection
    inter_AB = fuzzy_intersection(A, B)
    inter_ABC = fuzzy_intersection(inter_AB, C)
    print("Intersection (A ∩ B ∩ C):", inter_ABC)
    
    # Complement
    comp_A = fuzzy_complement(A, universe)
    comp_B = fuzzy_complement(B, universe)
    comp_C = fuzzy_complement(C, universe)
    print("Complement A':", comp_A)
    print("Complement B':", comp_B)
    print("Complement C':", comp_C)

if __name__ == "__main__":
    main()

Fuzzy Set A: {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
Fuzzy Set B: {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
Fuzzy Set C: {'x1': 0.3, 'x2': 0.9, 'x3': 0.5}
Union (A ∪ B ∪ C): {'x2': 0.9, 'x3': 0.6, 'x1': 0.8}
Intersection (A ∩ B ∩ C): {'x2': 0.4, 'x3': 0.2, 'x1': 0.3}
Complement A': {'x2': 0.6, 'x3': 0.4, 'x1': 0.19999999999999996}
Complement B': {'x2': 0.30000000000000004, 'x3': 0.8, 'x1': 0.5}
Complement C': {'x2': 0.09999999999999998, 'x3': 0.5, 'x1': 0.7}


In [25]:
# 13. Implement Fuzzy set operations – union, intersection and complement. Demonstrate De Morgan’s Law ( Complement of Union) with 2 fuzzy sets. 

def fuzzy_union(set1, set2):
    return {k: max(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() | set2.keys()}

def fuzzy_intersection(set1, set2):
    return {k: min(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() & set2.keys()}

def fuzzy_complement(set1, universe):
    return {k: 1 - set1.get(k, 0) for k in universe}

def main():
    A = {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
    B = {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
    universe = {'x1', 'x2', 'x3'}
    
    print("Fuzzy Set A:", A)
    print("Fuzzy Set B:", B)
    
    # De Morgan's Law: (A ∪ B)' = A' ∩ B'
    union_AB = fuzzy_union(A, B)
    comp_union_AB = fuzzy_complement(union_AB, universe)
    comp_A = fuzzy_complement(A, universe)
    comp_B = fuzzy_complement(B, universe)
    inter_comp_A_B = fuzzy_intersection(comp_A, comp_B)
    
    print("(A ∪ B)':", comp_union_AB)
    print("A' ∩ B':", inter_comp_A_B)
    print("De Morgan's Law holds:", comp_union_AB == inter_comp_A_B)

if __name__ == "__main__":
    main()

Fuzzy Set A: {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
Fuzzy Set B: {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
(A ∪ B)': {'x2': 0.30000000000000004, 'x3': 0.4, 'x1': 0.19999999999999996}
A' ∩ B': {'x2': 0.30000000000000004, 'x3': 0.4, 'x1': 0.19999999999999996}
De Morgan's Law holds: True


In [26]:
# 14. Implement Fuzzy set operations – union, intersection and complement.Demonstrate De Morgan’s Law ( Complement of Intersection) with 2 fuzzy sets. 

def fuzzy_union(set1, set2):
    return {k: max(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() | set2.keys()}

def fuzzy_intersection(set1, set2):
    return {k: min(set1.get(k, 0), set2.get(k, 0)) for k in set1.keys() & set2.keys()}

def fuzzy_complement(set1, universe):
    return {k: 1 - set1.get(k, 0) for k in universe}

def main():
    A = {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
    B = {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
    universe = {'x1', 'x2', 'x3'}
    
    print("Fuzzy Set A:", A)
    print("Fuzzy Set B:", B)
    
    # De Morgan's Law: (A ∩ B)' = A' ∪ B'
    inter_AB = fuzzy_intersection(A, B)
    comp_inter_AB = fuzzy_complement(inter_AB, universe)
    comp_A = fuzzy_complement(A, universe)
    comp_B = fuzzy_complement(B, universe)
    union_comp_A_B = fuzzy_union(comp_A, comp_B)
    
    print("(A ∩ B)':", comp_inter_AB)
    print("A' ∪ B':", union_comp_A_B)
    print("De Morgan's Law holds:", comp_inter_AB == union_comp_A_B)

if __name__ == "__main__":
    main()

Fuzzy Set A: {'x1': 0.8, 'x2': 0.4, 'x3': 0.6}
Fuzzy Set B: {'x1': 0.5, 'x2': 0.7, 'x3': 0.2}
(A ∩ B)': {'x2': 0.6, 'x3': 0.8, 'x1': 0.5}
A' ∪ B': {'x2': 0.6, 'x3': 0.8, 'x1': 0.5}
De Morgan's Law holds: True


In [27]:
# 15. Implement any two-player game ( Modified Tic-Tac-Toe, Nim Game,
# Connect Four Game or Gomoku Game ) using min-max algorithm such
# that in every play either computer wins or it is a draw. 

import math

# Initialize board
board = [' ' for _ in range(9)]

def print_board(board):
    for i in range(3):
        print(board[3*i] + "|" + board[3*i+1] + "|" + board[3*i+2])
        if i < 2:
            print("-+-+-")

def check_winner(board, player):
    win_positions = [
        (0,1,2), (3,4,5), (6,7,8),  
        (0,3,6), (1,4,7), (2,5,8),  
        (0,4,8), (2,4,6)            
    ]
    for pos in win_positions:
        if board[pos[0]] == board[pos[1]] == board[pos[2]] == player:
            return True
    return False

def is_full(board):
    return ' ' not in board

# Minimax algorithm
def minimax(board, is_maximizing):
    if check_winner(board, 'O'):
        return 1
    if check_winner(board, 'X'):
        return -1
    if is_full(board):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'
                score = minimax(board, False)
                board[i] = ' '
                best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'
                score = minimax(board, True)
                board[i] = ' '
                best_score = min(score, best_score)
        return best_score

def computer_move(board):
    best_score = -math.inf
    move = None
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'O'
            score = minimax(board, False)
            board[i] = ' '
            if score > best_score:
                best_score = score
                move = i
    board[move] = 'O'

def play_game():
    print("Welcome to Tic-Tac-Toe!")
    print_board(board)

    while True:
        move = int(input("Enter your move (1-9): ")) - 1
        if board[move] != ' ':
            print("Invalid move. Try again.")
            continue
        board[move] = 'X'

        if check_winner(board, 'X'):
            print_board(board)
            print("You win!")
            break

        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

        computer_move(board)
        print("\nComputer's move:")
        print_board(board)

        if check_winner(board, 'O'):
            print("Computer wins!")
            break

        if is_full(board):
            print("It's a draw!")
            break

# Start the game
play_game()

Welcome to Tic-Tac-Toe!
 | | 
-+-+-
 | | 
-+-+-
 | | 


Enter your move (1-9):  1



Computer's move:
X| | 
-+-+-
 |O| 
-+-+-
 | | 


Enter your move (1-9):  9



Computer's move:
X|O| 
-+-+-
 |O| 
-+-+-
 | |X


Enter your move (1-9):  8



Computer's move:
X|O| 
-+-+-
 |O| 
-+-+-
O|X|X


Enter your move (1-9):  3



Computer's move:
X|O|X
-+-+-
 |O|O
-+-+-
O|X|X


Enter your move (1-9):  4


X|O|X
-+-+-
X|O|O
-+-+-
O|X|X
It's a draw!


In [29]:
# 16. Implement any two-player game ( Modified Tic-Tac-Toe, Nim Game,
# Connect Four Game or Gomoku Game ) using min-max algorithm such
# that in every play either computer loses or it is a draw

import math

board = [' ' for _ in range(9)]

def print_board(board):
    for i in range(3):
        print(board[3*i] + "|" + board[3*i+1] + "|" + board[3*i+2])
        if i < 2:
            print("-+-+-")

def check_winner(board, player):
    win_positions = [
        (0,1,2), (3,4,5), (6,7,8),  
        (0,3,6), (1,4,7), (2,5,8),  
        (0,4,8), (2,4,6)            
    ]
    for pos in win_positions:
        if board[pos[0]] == board[pos[1]] == board[pos[2]] == player:
            return True
    return False

def is_full(board):
    return ' ' not in board

# Minimax algorithm (help human win)
def minimax(board, is_computer_turn):
    if check_winner(board, 'X'):
        return 1  # Human wins
    if check_winner(board, 'O'):
        return -1  # Computer wins
    if is_full(board):
        return 0  # Draw

    if is_computer_turn:
        best_score = math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'
                score = minimax(board, False)
                board[i] = ' '
                best_score = min(score, best_score)
        return best_score
    else:
        best_score = -math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'
                score = minimax(board, True)
                board[i] = ' '
                best_score = max(score, best_score)
        return best_score

# Computer move (intentionally weak)
def computer_move(board):
    worst_score = math.inf
    move = None
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'O'
            score = minimax(board, False)
            board[i] = ' '
            if score < worst_score:
                worst_score = score
                move = i
    board[move] = 'O'

# Main game loop
def play_game():
    print("Welcome to Tic-Tac-Toe! (Computer plays badly)")
    print_board(board)

    while True:
        # Player move
        move = int(input("Enter your move (1-9): ")) - 1
        if board[move] != ' ':
            print("Invalid move. Try again.")
            continue
        board[move] = 'X'

        # Check if player wins
        if check_winner(board, 'X'):
            print_board(board)
            print("You win!")
            break

        # Check draw
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

        # Computer move
        computer_move(board)
        print("\nComputer's move:")
        print_board(board)

        # Check if computer wins
        if check_winner(board, 'O'):
            print("Computer wins! (very rare)")
            break

        # Check draw
        if is_full(board):
            print("It's a draw!")
            break

# Start the game
play_game()

Welcome to Tic-Tac-Toe! (Computer plays badly)
 | | 
-+-+-
 | | 
-+-+-
 | | 


Enter your move (1-9):  1



Computer's move:
X| | 
-+-+-
 |O| 
-+-+-
 | | 


Enter your move (1-9):  9



Computer's move:
X|O| 
-+-+-
 |O| 
-+-+-
 | |X


Enter your move (1-9):  8



Computer's move:
X|O| 
-+-+-
 |O| 
-+-+-
O|X|X


Enter your move (1-9):  3



Computer's move:
X|O|X
-+-+-
 |O|O
-+-+-
O|X|X


Enter your move (1-9):  4


X|O|X
-+-+-
X|O|O
-+-+-
O|X|X
It's a draw!


In [30]:
# 17. Implement a simple Multi-Layer Perceptron with N binary inputs, two hidden layers and one binary output. Display the final weight matrices, bias
# values and the number of steps. Note that random values are assigned to weight matrices and bias in each step. 

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mlp_train(inputs, target, n_hidden1, n_hidden2, epochs=1000):
    n_inputs = len(inputs[0])
    w1 = np.random.randn(n_inputs, n_hidden1)
    b1 = np.random.randn(n_hidden1)
    w2 = np.random.randn(n_hidden1, n_hidden2)
    b2 = np.random.randn(n_hidden2)
    w3 = np.random.randn(n_hidden2, 1)
    b3 = np.random.randn(1)
    
    for epoch in range(epochs):
        # Forward pass
        h1 = sigmoid(np.dot(inputs, w1) + b1)
        h2 = sigmoid(np.dot(h1, w2) + b2)
        output = sigmoid(np.dot(h2, w3) + b3)
        
        # Simple update (random for simplicity)
        error = np.mean((output - target) ** 2)
        if error < 0.01:
            break
        w1 += np.random.randn(*w1.shape) * 0.01
        b1 += np.random.randn(*b1.shape) * 0.01
        w2 += np.random.randn(*w2.shape) * 0.01
        b2 += np.random.randn(*b2.shape) * 0.01
        w3 += np.random.randn(*w3.shape) * 0.01
        b3 += np.random.randn(*b3.shape) * 0.01
    
    return w1, b1, w2, b2, w3, b3, epoch + 1

def main():
    n = int(input("Enter number of inputs: "))
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Example for 2 inputs
    target = np.array([[0], [1], [1], [0]])  # XOR-like
    w1, b1, w2, b2, w3, b3, steps = mlp_train(inputs, target, 4, 4)
    print("Final Weights W1:\n", w1)
    print("Final Biases B1:", b1)
    print("Final Weights W2:\n", w2)
    print("Final Biases B2:", b2)
    print("Final Weights W3:\n", w3)
    print("Final Biases B3:", b3)
    print("Steps:", steps)

if __name__ == "__main__":
    main()

Enter number of inputs:  3


Final Weights W1:
 [[ 0.29686811 -0.17743034  1.25053061  0.06308815]
 [-0.03242416  0.61039214  0.07234795  0.80746368]]
Final Biases B1: [-0.64408504  1.03015788 -0.928676   -0.24203955]
Final Weights W2:
 [[ 0.98483412  0.49930965  0.67544276  2.15609834]
 [-1.08846413  0.36652017  0.45314052 -0.23379485]
 [-1.32918792  0.57210768 -0.23526393  1.07604778]
 [-0.76722007 -1.04616883 -0.31866441  0.07011615]]
Final Biases B2: [-0.77744504 -0.64280256  0.66566995  1.43516117]
Final Weights W3:
 [[-0.34833746]
 [-1.29362171]
 [-2.41571271]
 [ 1.05689465]]
Final Biases B3: [1.2058613]
Steps: 1000


In [31]:
# 18. Implement a simple Multi-Layer Perceptron with 4 binary inputs, one hidden layer and two binary outputs. Display the final weight matrices, bias
# values and the number of steps. Note that random values are assigned to weight matrices and bias in each step. 

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mlp_train(inputs, target, n_hidden, epochs=1000):
    n_inputs = len(inputs[0])
    w1 = np.random.randn(n_inputs, n_hidden)
    b1 = np.random.randn(n_hidden)
    w2 = np.random.randn(n_hidden, 2)
    b2 = np.random.randn(2)
    
    for epoch in range(epochs):
        # Forward pass
        h1 = sigmoid(np.dot(inputs, w1) + b1)
        output = sigmoid(np.dot(h1, w2) + b2)
        
        # Simple update
        error = np.mean((output - target) ** 2)
        if error < 0.01:
            break
        w1 += np.random.randn(*w1.shape) * 0.01
        b1 += np.random.randn(*b1.shape) * 0.01
        w2 += np.random.randn(*w2.shape) * 0.01
        b2 += np.random.randn(*b2.shape) * 0.01
    
    return w1, b1, w2, b2, epoch + 1

def main():
    inputs = np.array([[0, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 0, 1, 1]]) 
    target = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    w1, b1, w2, b2, steps = mlp_train(inputs, target, 4)
    print("Final Weights W1:\n", w1)
    print("Final Biases B1:", b1)
    print("Final Weights W2:\n", w2)
    print("Final Biases B2:", b2)
    print("Steps:", steps)

if __name__ == "__main__":
    main()

Final Weights W1:
 [[ 2.17746141  0.25003926 -0.19833868  1.6565097 ]
 [-0.4939328   0.98913609  0.40967405 -1.06671094]
 [ 0.36401239 -2.24055891  0.52617529  0.94531316]
 [-1.51516975  1.27861684 -0.15993574  1.84184892]]
Final Biases B1: [ 0.24332285 -1.73297197  1.31064093  0.61315346]
Final Weights W2:
 [[-1.2966549   1.09983588]
 [-0.41155184 -1.05471389]
 [ 0.54421438 -0.7882773 ]
 [ 1.37762155  0.30982579]]
Final Biases B2: [-0.04956982 -0.11123091]
Steps: 1000


In [32]:
# 19. Implement a simple Multi-Layer Perceptron with N binary inputs, two hidden layers and one output. Use backpropagation and Sigmoid function
# as activation function

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    return x * (1 - x)

def mlp_train(inputs, target, n_hidden1, n_hidden2, epochs=1000, lr=0.1):
    n_inputs = len(inputs[0])
    w1 = np.random.randn(n_inputs, n_hidden1)
    b1 = np.random.randn(n_hidden1)
    w2 = np.random.randn(n_hidden1, n_hidden2)
    b2 = np.random.randn(n_hidden2)
    w3 = np.random.randn(n_hidden2, 1)
    b3 = np.random.randn(1)
    
    for _ in range(epochs):
        # Forward
        z1 = np.dot(inputs, w1) + b1
        h1 = sigmoid(z1)
        z2 = np.dot(h1, w2) + b2
        h2 = sigmoid(z2)
        z3 = np.dot(h2, w3) + b3
        output = sigmoid(z3)
        
        # Backward
        error = output - target
        delta3 = error * sigmoid_deriv(output)
        error_h2 = np.dot(delta3, w3.T)
        delta2 = error_h2 * sigmoid_deriv(h2)
        error_h1 = np.dot(delta2, w2.T)
        delta1 = error_h1 * sigmoid_deriv(h1)
        
        # Update
        w3 -= lr * np.dot(h2.T, delta3)
        b3 -= lr * np.sum(delta3, axis=0)
        w2 -= lr * np.dot(h1.T, delta2)
        b2 -= lr * np.sum(delta2, axis=0)
        w1 -= lr * np.dot(inputs.T, delta1)
        b1 -= lr * np.sum(delta1, axis=0)
    
    return w1, b1, w2, b2, w3, b3

def main():
    n = int(input("Enter number of inputs: "))
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Example for 2 inputs
    target = np.array([[0], [1], [1], [0]])  # XOR-like
    w1, b1, w2, b2, w3, b3 = mlp_train(inputs, target, 4, 4)
    print("Final Weights W1:\n", w1)
    print("Final Biases B1:", b1)
    print("Final Weights W2:\n", w2)
    print("Final Biases B2:", b2)
    print("Final Weights W3:\n", w3)
    print("Final Biases B3:", b3)

if __name__ == "__main__":
    main()

Enter number of inputs:  2


Final Weights W1:
 [[ 0.69598764 -0.34340302 -0.18141699  2.09146907]
 [-0.7998137  -0.79389671  0.91768441  1.55900912]]
Final Biases B1: [ 2.13707375 -2.0338758   1.48020557 -0.27103883]
Final Weights W2:
 [[-1.99115912 -1.98868498 -0.34293221 -1.50036283]
 [ 0.82356696  0.00821677  1.32350168  1.72406384]
 [ 0.32405189  0.73157791  1.4836102  -0.26653063]
 [ 2.08326857  0.3488095  -0.89509433  1.53424146]]
Final Biases B2: [0.78193056 0.05862468 0.92794818 1.62484833]
Final Weights W3:
 [[ 1.46218596]
 [ 1.04293722]
 [-2.19347484]
 [-0.00375689]]
Final Biases B3: [0.39118766]


In [33]:
# 20. Implement a simple Multi-Layer Perceptron with N binary inputs, two hidden layers and one output. Use backpropagation and ReLU function as
# activation function. 

import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_deriv(x):
    return np.where(x > 0, 1, 0)

def mlp_train(inputs, target, n_hidden1, n_hidden2, epochs=1000, lr=0.01):
    n_inputs = len(inputs[0])
    w1 = np.random.randn(n_inputs, n_hidden1)
    b1 = np.random.randn(n_hidden1)
    w2 = np.random.randn(n_hidden1, n_hidden2)
    b2 = np.random.randn(n_hidden2)
    w3 = np.random.randn(n_hidden2, 1)
    b3 = np.random.randn(1)
    
    for _ in range(epochs):
        # Forward
        z1 = np.dot(inputs, w1) + b1
        h1 = relu(z1)
        z2 = np.dot(h1, w2) + b2
        h2 = relu(z2)
        z3 = np.dot(h2, w3) + b3
        output = relu(z3)
        
        # Backward
        error = output - target
        delta3 = error * relu_deriv(output)
        error_h2 = np.dot(delta3, w3.T)
        delta2 = error_h2 * relu_deriv(h2)
        error_h1 = np.dot(delta2, w2.T)
        delta1 = error_h1 * relu_deriv(h1)
        
        # Update
        w3 -= lr * np.dot(h2.T, delta3)
        b3 -= lr * np.sum(delta3, axis=0)
        w2 -= lr * np.dot(h1.T, delta2)
        b2 -= lr * np.sum(delta2, axis=0)
        w1 -= lr * np.dot(inputs.T, delta1)
        b1 -= lr * np.sum(delta1, axis=0)
    
    return w1, b1, w2, b2, w3, b3

def main():
    n = int(input("Enter number of inputs: "))
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  
    target = np.array([[0], [1], [1], [0]]) 
    w1, b1, w2, b2, w3, b3 = mlp_train(inputs, target, 4, 4)
    print("Final Weights W1:\n", w1)
    print("Final Biases B1:", b1)
    print("Final Weights W2:\n", w2)
    print("Final Biases B2:", b2)
    print("Final Weights W3:\n", w3)
    print("Final Biases B3:", b3)

if __name__ == "__main__":
    main()

Enter number of inputs:  2


Final Weights W1:
 [[-1.21088075  0.38091927 -0.25056585 -0.24245423]
 [-1.39464791  0.43122439  0.6590803   1.55701826]]
Final Biases B1: [-1.5812299  -0.59015922  2.21127094  0.07865528]
Final Weights W2:
 [[-0.61223284 -0.09008656  0.61357986 -0.34958252]
 [-0.8148057   0.88100725 -0.34827611 -0.44077822]
 [ 0.31516405 -1.010588   -0.03070052 -0.11878813]
 [-0.14914177  0.34998364  0.66397738 -2.90434764]]
Final Biases B2: [ 1.86044185 -0.96350014 -0.28704495  0.01640651]
Final Weights W3:
 [[-0.88115125]
 [-0.89978117]
 [-1.37621953]
 [-0.66556735]]
Final Biases B3: [0.86246375]


In [38]:
# 21. Implement a simple Multi-Layer Perceptron with N binary inputs, two hidden layers and one output. Use backpropagation and Tanh function as
# activation function. 

import numpy as np

def tanh(x):
    return np.tanh(x)

def tanh_deriv(x):
    return 1 - np.tanh(x) ** 2

def mlp_train(inputs, target, n_hidden1, n_hidden2, epochs=1000, lr=0.1):
    n_inputs = len(inputs[0])
    w1 = np.random.randn(n_inputs, n_hidden1)
    b1 = np.random.randn(n_hidden1)
    w2 = np.random.randn(n_hidden1, n_hidden2)
    b2 = np.random.randn(n_hidden2)
    w3 = np.random.randn(n_hidden2, 1)
    b3 = np.random.randn(1)
    
    for _ in range(epochs):
        # Forward
        z1 = np.dot(inputs, w1) + b1
        h1 = tanh(z1)
        z2 = np.dot(h1, w2) + b2
        h2 = tanh(z2)
        z3 = np.dot(h2, w3) + b3
        output = tanh(z3)
        
        # Backward
        error = output - target
        delta3 = error * tanh_deriv(output)
        error_h2 = np.dot(delta3, w3.T)
        delta2 = error_h2 * tanh_deriv(h2)
        error_h1 = np.dot(delta2, w2.T)
        delta1 = error_h1 * tanh_deriv(h1)
        
        # Update
        w3 -= lr * np.dot(h2.T, delta3)
        b3 -= lr * np.sum(delta3, axis=0)
        w2 -= lr * np.dot(h1.T, delta2)
        b2 -= lr * np.sum(delta2, axis=0)
        w1 -= lr * np.dot(inputs.T, delta1)
        b1 -= lr * np.sum(delta1, axis=0)
    
    return w1, b1, w2, b2, w3, b3

def main():
    n = int(input("Enter number of inputs: "))
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Example
    target = np.array([[0], [1], [1], [0]])  # XOR-like
    w1, b1, w2, b2, w3, b3 = mlp_train(inputs, target, 4, 4)
    print("Final Weights W1:\n", w1)
    print("Final Biases B1:", b1)
    print("Final Weights W2:\n", w2)
    print("Final Biases B2:", b2)
    print("Final Weights W3:\n", w3)
    print("Final Biases B3:", b3)

if __name__ == "__main__":
    main()

Enter number of inputs:  2


Final Weights W1:
 [[ 1.37066171 -0.60421971 -0.34179889 -1.65869423]
 [-1.58105014 -0.41055684  0.64600089  1.32550643]]
Final Biases B1: [-0.79108959 -0.82606283 -1.22745137 -0.81104806]
Final Weights W2:
 [[-0.28006095 -1.34055822 -0.0899361   1.51325261]
 [ 0.89411442  0.7832913  -0.51822854 -1.14412372]
 [-1.00084686  0.59080615  0.24834576  0.56281678]
 [-1.80900764 -1.7364352  -0.56965023 -0.73405869]]
Final Biases B2: [-0.74907622 -0.1643337   0.80710399 -0.98729506]
Final Weights W3:
 [[-0.74429987]
 [-1.52760687]
 [ 0.7168349 ]
 [ 0.81753544]]
Final Biases B3: [1.55849241]


In [1]:
# 22. Write a program to read a text file with at least 30 sentences and 200 words
# and perform the following tasks in the given sequence.
# a. Text cleaning by removing punctuation/special characters, numbers and extra white spaces. Use regular expression for the same.
# b. Convert text to lowercase
# c. Tokenization
# d. Remove stop words
# e. Correct misspelled words 

import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

def process_text(filename):
    # Read file
    with open(filename, 'r') as file:
        text = file.read()
    
    # a. Clean text
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    
    # b. Convert to lowercase
    text = text.lower()
    
    # c. Tokenization
    tokens = word_tokenize(text)
    
    # d. Remove stop words
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    
    # e. Correct spelling
    corrected_tokens = [str(TextBlob(token).correct()) for token in tokens]
    
    return corrected_tokens

def main():
    filename = 'input.txt'  
    result = process_text(filename)
    print("Processed Tokens:", result)

if __name__ == "__main__":
    main()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dhaval\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dhaval\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dhaval\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


Processed Tokens: ['artificial', 'intelligence', 'fascinating', 'field', 'changed', 'way', 'live', 'machine', 'learning', 'key', 'part', 'ai', 'allows', 'computers', 'learn', 'data', 'neutral', 'network', 'powerful', 'tools', 'recognize', 'patterns', 'images', 'text', 'sound', 'deep', 'learning', 'uses', 'many', 'layers', 'neutral', 'network', 'makes', 'effective', 'complex', 'tasks', 'ai', 'used', 'many', 'industries', 'selfdriving', 'cars', 'rely', 'ai', 'navigable', 'roads', 'healthcare', 'ai', 'helps', 'doctors', 'diagnose', 'diseases', 'analyze', 'rays', 'mrs', 'quickly', 'virtual', 'assistants', 'like', 'sir', 'use', 'ai', 'understand', 'speech', 'respond', 'questions', 'seconds', 'however', 'ai', 'challenges', 'bias', 'data', 'lead', 'unfair', 'results', 'example', 'facial', 'recognition', 'may', 'work', 'well', 'people', 'privacy', 'another', 'concern', 'ai', 'systems', 'collect', 'lot', 'data', 'data', 'must', 'protected', 'ethics', 'ai', 'hot', 'topic', 'ai', 'make', 'decisio

In [2]:
# 23. Write a program to read a text file with at least 30 sentences and 200 words
# and perform the following tasks in the given sequence.
# a. Text cleaning by removing punctuation/special characters, numbers and extra white spaces. Use regular expression for the same.
# b. Convert text to lowercase
# c. Stemming and Lemmatization
# d. Create a list of 3 consecutive words after lemmatization

import re
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import nltk
nltk.download('punkt')
nltk.download('wordnet')

def process_text(filename):
    # Read file
    with open(filename, 'r') as file:
        text = file.read()
    
    # a. Clean text
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    
    # b. Convert to lowercase
    text = text.lower()
    
    # c. Stemming and Lemmatization
    tokens = word_tokenize(text)
    stemmer = PorterStemmer()
    lemmatizer = WordNetLemmatizer()
    stemmed = [stemmer.stem(token) for token in tokens]
    lemmatized = [lemmatizer.lemmatize(token) for token in tokens]
    
    # d. Create trigrams
    trigrams = [lemmatized[i:i+3] for i in range(len(lemmatized)-2)]
    
    return stemmed, lemmatized, trigrams

def main():
    filename = 'input.txt' 
    stemmed, lemmatized, trigrams = process_text(filename)
    print("Stemmed Tokens:", stemmed[:10])
    print("Lemmatized Tokens:", lemmatized[:10])
    print("Trigrams:", trigrams[:5])

if __name__ == "__main__":
    main()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dhaval\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Dhaval\AppData\Roaming\nltk_data...


Stemmed Tokens: ['artifici', 'intelig', 'is', 'a', 'fascin', 'field', 'it', 'ha', 'chang', 'the']
Lemmatized Tokens: ['artificial', 'inteligence', 'is', 'a', 'fascinating', 'field', 'it', 'ha', 'changed', 'the']
Trigrams: [['artificial', 'inteligence', 'is'], ['inteligence', 'is', 'a'], ['is', 'a', 'fascinating'], ['a', 'fascinating', 'field'], ['fascinating', 'field', 'it']]


In [1]:
# 24. Write a program to read a 3 text files on any technical concept with at least 20 sentences and 150 words. Implement one-hot encoding. 

from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

def one_hot_encoding(filenames):
    texts = []
    for filename in filenames:
        with open(filename, 'r') as file:
            texts.append(file.read())
    
    # Create vocabulary
    vectorizer = CountVectorizer(binary=True)
    X = vectorizer.fit_transform(texts)
    vocab = vectorizer.get_feature_names_out()
    one_hot = X.toarray()
    
    return vocab, one_hot

def main():
    filenames = ['text1.txt', 'text2.txt', 'text3.txt']  
    vocab, one_hot = one_hot_encoding(filenames)
    print("Vocabulary:", vocab[:10])
    print("One-Hot Matrix (first 5 words):\n", one_hot[:, :5])

if __name__ == "__main__":
    main()

Vocabulary: ['2022' '2023' 'accuracy' 'address' 'addressing' 'adjusts' 'age'
 'algorithm' 'algorithms' 'also']
One-Hot Matrix (first 5 words):
 [[0 1 0 0 1]
 [1 0 1 1 0]
 [0 1 0 0 0]]


In [3]:
# 25. Write a program to read a 3 text files on a movie review with at least 20 sentences and 150 words. Implement bag of words. 

from sklearn.feature_extraction.text import CountVectorizer

def bag_of_words(filenames):
    texts = []
    for filename in filenames:
        with open(filename, 'r') as file:
            texts.append(file.read())
    
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(texts)
    vocab = vectorizer.get_feature_names_out()
    bow = X.toarray()
    
    return vocab, bow

def main():
    filenames = ['text1.txt', 'text2.txt', 'text3.txt']  
    vocab, bow = bag_of_words(filenames)
    print("Vocabulary:", vocab[:10])
    print("Bag of Words Matrix (first 5 words):\n", bow[:, :5])

if __name__ == "__main__":
    main()

Vocabulary: ['2022' '2023' 'accuracy' 'address' 'addressing' 'adjusts' 'age'
 'algorithm' 'algorithms' 'also']
Bag of Words Matrix (first 5 words):
 [[0 1 0 0 1]
 [1 0 1 1 0]
 [0 1 0 0 0]]


In [4]:
# 26. Write a program to read a 3 text files a tourist place with at least 20 sentences and 150 words. Implement TF-IDF. 

from sklearn.feature_extraction.text import TfidfVectorizer

def tf_idf(filenames):
    texts = []
    for filename in filenames:
        with open(filename, 'r') as file:
            texts.append(file.read())
    
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(texts)
    vocab = vectorizer.get_feature_names_out()
    tfidf = X.toarray()
    
    return vocab, tfidf

def main():
    filenames = ['text1.txt', 'text2.txt', 'text3.txt']  
    vocab, tfidf = tf_idf(filenames)
    print("Vocabulary:", vocab[:10])
    print("TF-IDF Matrix (first 5 words):\n", tfidf[:, :5])

if __name__ == "__main__":
    main()

Vocabulary: ['2022' '2023' 'accuracy' 'address' 'addressing' 'adjusts' 'age'
 'algorithm' 'algorithms' 'also']
TF-IDF Matrix (first 5 words):
 [[0.         0.05198682 0.         0.         0.06835643]
 [0.06982469 0.         0.06982469 0.06982469 0.        ]
 [0.         0.05247299 0.         0.         0.        ]]
